version: '3'

services:
  sleekwaredb-api:
    container_name: swdb-api
    build:
      context: ./backend/
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./backend/:/var/www/html
      - ./backend/.docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - sleekwaredb-network

  sleekwaredb-nginx:
    container_name: swdb-nginx
    image: nginx:alpine
    volumes:
      - ./backend/:/var/www/html
      - ./backend/.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    tty: true
    ports:
      - "${BACKEND_PORT}:80"
    networks:
      - sleekwaredb-network

  sleekwaredb-composer:
    container_name: swdb-composer
    image: composer:latest
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - sleekwaredb-network

  sleekwaredb-frontend:
    container_name: swdb-app
    build:
      context: ./frontend/
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./frontend/:/app
    ports:
      - "3001:3000"
    networks:
      - sleekwaredb-network

networks:
  sleekwaredb-network:
    external: true
